import { FormEvent, useState } from 'react';
import { api } from '../api';
import { ViewType } from '../types';
import { ArrowLeft, Lock, ShieldCheck } from 'lucide-react';

export default function SecurityPage({ setView }: { setView: (view: ViewType) => void }) {
  const [current,setCurrent]=useState(''); const [next,setNext]=useState(''); const [confirmation,setConfirmation]=useState(''); const [message,setMessage]=useState(''); const [error,setError]=useState('');
  const submit=async(event:FormEvent)=>{event.preventDefault();setError('');setMessage('');if(next!==confirmation)return setError('Las contraseñas no coinciden.');try{const result=await api.changePassword(current,next);setMessage(result.message);setCurrent('');setNext('');setConfirmation('');}catch(cause){setError(cause instanceof Error?cause.message:'No se pudo cambiar la contraseña.');}};
  return <div className="mx-auto max-w-xl px-6 py-14"><button onClick={()=>setView('dashboard')} className="mb-6 flex items-center gap-2 text-sm font-bold text-brand-teal"><ArrowLeft className="h-4 w-4"/>Volver</button><div className="geometric-card p-8"><ShieldCheck className="h-9 w-9 text-brand-teal"/><h1 className="mt-3 text-2xl font-extrabold text-brand-blue-dark">Seguridad de la cuenta</h1><p className="mt-2 text-sm text-slate-500">Cambiarla revoca las sesiones anteriores.</p><form onSubmit={submit} className="mt-7 space-y-4">{message&&<p className="rounded bg-emerald-50 p-3 text-sm text-emerald-700">{message}</p>}{error&&<p className="rounded bg-red-50 p-3 text-sm text-red-700">{error}</p>}{[['Contraseña actual',current,setCurrent],['Contraseña nueva',next,setNext],['Confirmar contraseña',confirmation,setConfirmation]].map(([label,value,setter])=><label key={label as string} className="block text-xs font-bold text-slate-600">{label as string}<input type="password" required className="mt-2 w-full rounded border p-3" value={value as string} onChange={e=>(setter as (v:string)=>void)(e.target.value)}/></label>)}<button className="flex w-full justify-center gap-2 rounded bg-brand-teal p-3 text-xs font-bold uppercase text-white"><Lock className="h-4 w-4"/>Cambiar contraseña</button></form></div></div>;
}
