import { FormEvent, useState } from 'react';
import { api } from '../api';
import { ViewType } from '../types';
import { ArrowLeft, Download, KeyRound, Lock, ShieldCheck } from 'lucide-react';
import PasswordInput from './PasswordInput';
import { useToast } from './ToastProvider';

interface SecurityPageProps {
  setView: (view: ViewType) => void;
  isAdmin: boolean;
  mfaEnabled: boolean;
  onAccountDeleted: () => void;
}

export default function SecurityPage({ setView, isAdmin, mfaEnabled: initialMfaEnabled, onAccountDeleted }: SecurityPageProps) {
  const { toast } = useToast();
  const [current,setCurrent]=useState(''); const [next,setNext]=useState(''); const [confirmation,setConfirmation]=useState(''); const [message,setMessage]=useState(''); const [error,setError]=useState('');
  const [deletePassword,setDeletePassword]=useState(''); const [deleteConfirmation,setDeleteConfirmation]=useState(''); const [deleteError,setDeleteError]=useState('');
  const [mfaEnabled,setMfaEnabled]=useState(initialMfaEnabled); const [mfaPassword,setMfaPassword]=useState(''); const [mfaCode,setMfaCode]=useState(''); const [mfaError,setMfaError]=useState('');
  const [qrCode,setQrCode]=useState(''); const [manualKey,setManualKey]=useState(''); const [recoveryCodes,setRecoveryCodes]=useState<string[]>([]);
  const [disablePassword,setDisablePassword]=useState(''); const [disableCode,setDisableCode]=useState('');

  const submit=async(event:FormEvent)=>{event.preventDefault();setError('');setMessage('');if(next!==confirmation)return setError('Las contraseñas no coinciden.');try{const result=await api.changePassword(current,next);setMessage(result.message);setCurrent('');setNext('');setConfirmation('');}catch(cause){setError(cause instanceof Error?cause.message:'No se pudo cambiar la contraseña.');}};
  const exportData=async()=>{try{const data=await api.exportAccount();const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const anchor=document.createElement('a');anchor.href=url;anchor.download=`vigentegt-mis-datos-${new Date().toISOString().slice(0,10)}.json`;anchor.click();URL.revokeObjectURL(url);}catch(cause){toast(cause instanceof Error?cause.message:'No se pudieron descargar tus datos.','error');}};
  const deleteAccount=async(event:FormEvent)=>{event.preventDefault();setDeleteError('');if(deleteConfirmation!=='ELIMINAR')return setDeleteError('Escribe ELIMINAR exactamente.');if(!confirm('Esta acción borrará definitivamente tu cuenta, documentos y alertas. ¿Deseas continuar?'))return;try{await api.deleteAccount(deletePassword,deleteConfirmation);onAccountDeleted();}catch(cause){setDeleteError(cause instanceof Error?cause.message:'No se pudo eliminar la cuenta.');}};
  const startMfa=async(event:FormEvent)=>{event.preventDefault();setMfaError('');try{const result=await api.setupMfa(mfaPassword);setQrCode(result.qrCode);setManualKey(result.manualKey);setMfaPassword('');}catch(cause){setMfaError(cause instanceof Error?cause.message:'No se pudo iniciar MFA.');}};
  const enableMfa=async(event:FormEvent)=>{event.preventDefault();setMfaError('');try{const result=await api.enableMfa(mfaCode);setRecoveryCodes(result.recoveryCodes);setMfaEnabled(true);setQrCode('');setManualKey('');setMfaCode('');toast('MFA fue activado correctamente.','success');}catch(cause){setMfaError(cause instanceof Error?cause.message:'No se pudo activar MFA.');}};
  const disableMfa=async(event:FormEvent)=>{event.preventDefault();setMfaError('');try{const result=await api.disableMfa(disablePassword,disableCode);toast(result.message,'success');setMfaEnabled(false);setDisablePassword('');setDisableCode('');}catch(cause){setMfaError(cause instanceof Error?cause.message:'No se pudo desactivar MFA.');}};
  const downloadRecoveryCodes=()=>{const url=URL.createObjectURL(new Blob([`Códigos de recuperación — Vigente GT\n\n${recoveryCodes.join('\n')}\n\nCada código funciona una sola vez.`],{type:'text/plain'}));const anchor=document.createElement('a');anchor.href=url;anchor.download='vigentegt-codigos-recuperacion.txt';anchor.click();URL.revokeObjectURL(url);};

  return <div className="mx-auto max-w-xl px-6 py-14">
    <button onClick={()=>setView(isAdmin?'admin':'dashboard')} className="mb-6 flex items-center gap-2 text-sm font-bold text-brand-teal"><ArrowLeft className="h-4 w-4"/>Volver</button>
    <div className="space-y-8">
      <div className={`geometric-card p-8 ${isAdmin&&!mfaEnabled?'border-amber-300 bg-amber-50/30':''}`}>
        <KeyRound className="h-9 w-9 text-brand-teal"/><h1 className="mt-3 text-2xl font-extrabold text-brand-blue-dark">Autenticación de dos pasos</h1>
        <p className="mt-2 text-sm text-slate-500">Usa una aplicación compatible con TOTP. {isAdmin?'Es obligatoria para acceder al panel administrativo.':'Es opcional y recomendada.'}</p>
        {mfaError&&<p className="mt-4 rounded bg-red-50 p-3 text-sm text-red-700">{mfaError}</p>}
        {recoveryCodes.length>0?<div className="mt-6 rounded border border-amber-200 bg-amber-50 p-5"><h2 className="font-bold text-amber-900">Guarda estos códigos ahora</h2><p className="mt-1 text-xs text-amber-800">No volverán a mostrarse. Cada uno funciona una sola vez.</p><div className="mt-4 grid grid-cols-2 gap-2 font-mono text-xs text-slate-800">{recoveryCodes.map(code=><code key={code}>{code}</code>)}</div><button onClick={downloadRecoveryCodes} className="mt-5 flex items-center gap-2 rounded bg-amber-900 px-4 py-2 text-xs font-bold text-white"><Download className="h-4 w-4"/>Descargar códigos</button><button onClick={()=>window.location.reload()} className="mt-3 w-full rounded border border-amber-800 p-2 text-xs font-bold text-amber-900">Ya guardé mis códigos</button></div>
        :!mfaEnabled&&!qrCode?<form onSubmit={startMfa} className="mt-6 space-y-4"><PasswordInput label="Confirma tu contraseña" value={mfaPassword} onChange={setMfaPassword} autoComplete="current-password" compact/><button className="w-full rounded bg-brand-teal p-3 text-xs font-bold uppercase text-white">Configurar MFA</button></form>
        :!mfaEnabled&&qrCode?<form onSubmit={enableMfa} className="mt-6 space-y-4 text-center"><img src={qrCode} alt="Código QR para configurar la aplicación autenticadora" className="mx-auto h-56 w-56 rounded border bg-white p-2"/><p className="text-xs text-slate-500">Si no puedes escanearlo, usa esta clave:</p><code className="block break-all rounded bg-slate-100 p-3 text-xs text-slate-800">{manualKey}</code><label className="block text-left text-xs font-bold text-slate-600">Código de 6 dígitos<input value={mfaCode} onChange={e=>setMfaCode(e.target.value.replace(/\D/g,'').slice(0,6))} inputMode="numeric" autoComplete="one-time-code" required pattern="\d{6}" className="mt-2 w-full rounded border p-3 text-center font-mono text-lg tracking-widest"/></label><button className="w-full rounded bg-brand-teal p-3 text-xs font-bold uppercase text-white">Verificar y activar</button></form>
        :<div className="mt-6"><p className="rounded bg-emerald-50 p-3 text-sm font-bold text-emerald-700">MFA está activado.</p>{!isAdmin&&<form onSubmit={disableMfa} className="mt-5 space-y-4 border-t pt-5"><p className="text-xs text-slate-500">Para desactivarlo confirma tu contraseña y un código actual o de recuperación.</p><PasswordInput label="Contraseña" value={disablePassword} onChange={setDisablePassword} autoComplete="current-password" compact/><label className="block text-xs font-bold text-slate-600">Código MFA<input value={disableCode} onChange={e=>setDisableCode(e.target.value)} required className="mt-2 w-full rounded border p-3 font-mono"/></label><button className="w-full rounded border border-red-300 p-3 text-xs font-bold uppercase text-red-700">Desactivar MFA</button></form>}</div>}
      </div>
      <div className="geometric-card p-8"><ShieldCheck className="h-9 w-9 text-brand-teal"/><h2 className="mt-3 text-2xl font-extrabold text-brand-blue-dark">Cambiar contraseña</h2><p className="mt-2 text-sm text-slate-500">Cambiarla revoca las sesiones anteriores.</p><form onSubmit={submit} className="mt-7 space-y-4">{message&&<p className="rounded bg-emerald-50 p-3 text-sm text-emerald-700">{message}</p>}{error&&<p className="rounded bg-red-50 p-3 text-sm text-red-700">{error}</p>}<PasswordInput label="Contraseña actual" value={current} onChange={setCurrent} autoComplete="current-password" compact/><PasswordInput label="Contraseña nueva" value={next} onChange={setNext} minLength={12} autoComplete="new-password" compact/><PasswordInput label="Confirmar contraseña" value={confirmation} onChange={setConfirmation} autoComplete="new-password" compact/><button className="flex w-full justify-center gap-2 rounded bg-brand-teal p-3 text-xs font-bold uppercase text-white"><Lock className="h-4 w-4"/>Cambiar contraseña</button></form></div>
      <div className="geometric-card p-8"><h2 className="text-xl font-extrabold text-brand-blue-dark">Tus datos</h2><p className="mt-2 text-sm text-slate-500">Descarga una copia legible de tu cuenta, consentimientos, documentos y entregas.</p><button onClick={exportData} className="mt-5 rounded border border-brand-blue px-4 py-2 text-xs font-bold uppercase text-brand-blue">Descargar mis datos</button></div>
      {!isAdmin&&<div className="rounded border border-red-200 bg-red-50/40 p-8"><h2 className="text-xl font-extrabold text-red-700">Eliminar mi cuenta</h2><p className="mt-2 text-sm text-red-700/80">El borrado es permanente e incluye documentos, alertas, consentimientos y registros de entrega asociados.</p><form onSubmit={deleteAccount} className="mt-5 space-y-4">{deleteError&&<p className="rounded bg-red-100 p-3 text-sm text-red-700">{deleteError}</p>}<PasswordInput label="Contraseña" value={deletePassword} onChange={setDeletePassword} autoComplete="current-password" compact/><label className="block text-xs font-bold text-red-700">Escribe ELIMINAR<input value={deleteConfirmation} onChange={e=>setDeleteConfirmation(e.target.value)} className="mt-2 w-full rounded border border-red-200 bg-white p-3 text-sm" autoComplete="off" required/></label><button className="w-full rounded bg-red-700 p-3 text-xs font-bold uppercase text-white">Eliminar definitivamente mi cuenta</button></form></div>}
    </div>
  </div>;
}
