import { FormEvent, useState } from 'react';
import { api } from '../api';
import { ViewType } from '../types';
import { ArrowLeft, Lock, ShieldCheck } from 'lucide-react';
import PasswordInput from './PasswordInput';

export default function SecurityPage({ setView, isAdmin, onAccountDeleted }: { setView: (view: ViewType) => void; isAdmin: boolean; onAccountDeleted: () => void }) {
  const [current,setCurrent]=useState(''); const [next,setNext]=useState(''); const [confirmation,setConfirmation]=useState(''); const [message,setMessage]=useState(''); const [error,setError]=useState('');
  const [deletePassword,setDeletePassword]=useState(''); const [deleteConfirmation,setDeleteConfirmation]=useState(''); const [deleteError,setDeleteError]=useState('');
  const submit=async(event:FormEvent)=>{event.preventDefault();setError('');setMessage('');if(next!==confirmation)return setError('Las contraseñas no coinciden.');try{const result=await api.changePassword(current,next);setMessage(result.message);setCurrent('');setNext('');setConfirmation('');}catch(cause){setError(cause instanceof Error?cause.message:'No se pudo cambiar la contraseña.');}};
  const exportData=async()=>{try{const data=await api.exportAccount();const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const anchor=document.createElement('a');anchor.href=url;anchor.download=`vigentegt-mis-datos-${new Date().toISOString().slice(0,10)}.json`;anchor.click();URL.revokeObjectURL(url);}catch(cause){setError(cause instanceof Error?cause.message:'No se pudieron descargar tus datos.');}};
  const deleteAccount=async(event:FormEvent)=>{event.preventDefault();setDeleteError('');if(deleteConfirmation!=='ELIMINAR')return setDeleteError('Escribe ELIMINAR exactamente.');if(!confirm('Esta acción borrará definitivamente tu cuenta, documentos y alertas. ¿Deseas continuar?'))return;try{await api.deleteAccount(deletePassword,deleteConfirmation);onAccountDeleted();}catch(cause){setDeleteError(cause instanceof Error?cause.message:'No se pudo eliminar la cuenta.');}};
  return <div className="mx-auto max-w-xl px-6 py-14"><button onClick={()=>setView('dashboard')} className="mb-6 flex items-center gap-2 text-sm font-bold text-brand-teal"><ArrowLeft className="h-4 w-4"/>Volver</button><div className="space-y-8"><div className="geometric-card p-8"><ShieldCheck className="h-9 w-9 text-brand-teal"/><h1 className="mt-3 text-2xl font-extrabold text-brand-blue-dark">Seguridad de la cuenta</h1><p className="mt-2 text-sm text-slate-500">Cambiarla revoca las sesiones anteriores.</p><form onSubmit={submit} className="mt-7 space-y-4">{message&&<p className="rounded bg-emerald-50 p-3 text-sm text-emerald-700">{message}</p>}{error&&<p className="rounded bg-red-50 p-3 text-sm text-red-700">{error}</p>}<PasswordInput label="Contraseña actual" value={current} onChange={setCurrent} autoComplete="current-password" compact/><PasswordInput label="Contraseña nueva" value={next} onChange={setNext} minLength={12} autoComplete="new-password" compact/><PasswordInput label="Confirmar contraseña" value={confirmation} onChange={setConfirmation} autoComplete="new-password" compact/><button className="flex w-full justify-center gap-2 rounded bg-brand-teal p-3 text-xs font-bold uppercase text-white"><Lock className="h-4 w-4"/>Cambiar contraseña</button></form></div><div className="geometric-card p-8"><h2 className="text-xl font-extrabold text-brand-blue-dark">Tus datos</h2><p className="mt-2 text-sm text-slate-500">Descarga una copia legible de tu cuenta, consentimientos, documentos y entregas.</p><button onClick={exportData} className="mt-5 rounded border border-brand-blue px-4 py-2 text-xs font-bold uppercase text-brand-blue">Descargar mis datos</button></div>{!isAdmin&&<div className="rounded border border-red-200 bg-red-50/40 p-8"><h2 className="text-xl font-extrabold text-red-700">Eliminar mi cuenta</h2><p className="mt-2 text-sm text-red-700/80">El borrado es permanente e incluye documentos, alertas, consentimientos y registros de entrega asociados.</p><form onSubmit={deleteAccount} className="mt-5 space-y-4">{deleteError&&<p className="rounded bg-red-100 p-3 text-sm text-red-700">{deleteError}</p>}<PasswordInput label="Contraseña" value={deletePassword} onChange={setDeletePassword} autoComplete="current-password" compact/><label className="block text-xs font-bold text-red-700">Escribe ELIMINAR<input value={deleteConfirmation} onChange={e=>setDeleteConfirmation(e.target.value)} className="mt-2 w-full rounded border border-red-200 bg-white p-3 text-sm" autoComplete="off" required/></label><button className="w-full rounded bg-red-700 p-3 text-xs font-bold uppercase text-white">Eliminar definitivamente mi cuenta</button></form></div>}</div></div>;
}
